github: ayush-that
patreon: your-patreon-username
open_collective: your-open-collective-username
ko_fi: your-ko-fi-username
tidelift: platform-name/package-name (e.g., npm/babel)
community_bridge: project-name (e.g., cloud-foundry)
liberapay: your-liberapay-username
issuehunt: your-issuehunt-username
lfx_crowdfunding: project-name (e.g., cloud-foundry)
polar: your-polar-username
buy_me_a_coffee: your-buy-me-a-coffee-username
custom: ['link1', 'link2', 'link3', 'link4']
